version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/client/insight"
    schedule:
      interval: "weekly"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
          - "@react-spring/*"
          - "@visx/*"
      insight-dev:
        dependency-type: "development"
        patterns:
          - "*"
      insight-prod:
        dependency-type: "production"
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/server"
    schedule:
      interval: "weekly"
