version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/client/insight"
    schedule:
      interval: "weekly"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
          - "@react-spring/*"
      insight:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/server"
    schedule:
      interval: "weekly"
