version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/client/insight"
    schedule:
      interval: "weekly"
    groups:
      insight:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/server"
    schedule:
      interval: "weekly"
    groups:
      server:
        patterns:
          - "*"
