extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:react/recommended"
  - "prettier"
  - "prettier/react"
  - "prettier/@typescript-eslint"
rules:
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/unbound-method": off
  "@typescript-eslint/no-unused-vars":
    - "error"
    - argsIgnorePattern: "^_"
  "@typescript-eslint/camelcase": off
  "@typescript-eslint/unbound-method":
    - "error"
    - ignoreStatic: true

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  project: "./tsconfig.json"
  sourceType: "module"
  ecmaFeatures:
    jsx: true

root: true
settings:
  react:
    version: "detect"
