extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended-type-checked"
  - "plugin:react-hooks/recommended"
  - "prettier"
rules:
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-unused-vars":
    - "error"
    - argsIgnorePattern: "^_"
  "@typescript-eslint/camelcase": off
  "@typescript-eslint/unbound-method":
    - "error"
    - ignoreStatic: true

parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - react-refresh
parserOptions:
  ecmaVersion: latest
  sourceType: "module"
  project: ./tsconfig.json

root: true
settings:
  react:
    version: "detect"
