name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
      - "insightapi-*"
      - "mwi-*"

jobs:
  server:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Server TestSuite
        timeout-minutes: 10
        run: |
          tzutil /s "Pacific Standard Time"
          dotnet run --project server/test `
              --coverage --coverage-output-format cobertura --coverage-output server-cov.xml

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: server\test\bin\Debug\net10.0\TestResults\server-cov.xml
          flags: server-unittests

      - name: Reverse proxy build
        run: dotnet build server/reverse-proxy

  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "latest"

      - uses: pnpm/action-setup@v6
        with:
          cache: true
          cache_dependency_path: client/insight/pnpm-lock.yaml
          package_json_file: client/insight/package.json

      - name: Install client deps
        run: pnpm --dir client/insight install --frozen-lockfile

      - name: Client Type Check
        run: pnpm --dir client/insight run type-check

      - name: Client Lint
        run: pnpm --dir client/insight run lint

      - name: Client Unit Test Suite
        run: pnpm --dir client/insight run test:unit

      - name: Client Integration Test Suite
        run: pnpm --dir client/insight run test:integration
